branch-defaults:
  master:
    environment: WordlistStorage-env-dev
    group_suffix: null
global:
  application_name: WordlistStorage
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Go 1.13.2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
