branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: WordlistStorage
  branch: null
  default_platform: Go 1.13.2
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  workspace_type: Application
